dist: xenial

language: go

go:
  - 1.12.x

install: true

notifications:
  email: false

before_install:
  - go get ./...

install:
  - go get github.com/mezeipetister/project_a
  
script:
  - go test -v -race ./...
