[development]
address = "localhost"
port = 8000
log = "normal"
template_dir = "./website/templates/"
assets_dir = "./website/assets/"

[production]
address = "localhost"
port = 8000
log = "critical"
template_dir = "./website/templates/"
assets_dir = "./website/assets/"